stages:
  - build
build-job:
  stage: build
  image: docker:24.0.5-cli
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd projekt
    - echo "DB_URL=jdbc:postgresql://database:5432/db_test" > backend/.env
    - echo "POSTGRES_USER=postgres" >> backend/.env
    - echo "POSTGRES_DB=db_test" >> backend/.env
    - echo "POSTGRES_PASSWORD=secret" >> backend/.env
    - docker compose create