stages:
  - build
  - test_backend
build-job:
  stage: build
  image: docker:24.0.5-cli
  services:
    - name: docker:24.0.5-dind
      alias: docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - touch projekt/.env
  script:
    - cd projekt
    - docker compose create
    - docker compose push
backend-test:
  stage: test_backend
  image: docker:24.0.5-cli
  services:
    - name: docker:24.0.5-dind
      alias: docker
  variables:
    POSTGRES_USER: test_user
    POSTGRES_DB: test_db
    POSTGRES_PASSWORD: test_pw # probably needs to be a secret too

    DB_URL: jdbc:postgresql://database:5432/test_db

    #JWT_SECRET: $JWT_SECRET

    #REFRESH_TOKEN_HMAC_SECRET: $REFRESH_TOKEN_HMAC_SECRET

    MAIL_HOST: mailhog
    MAIL_PORT: 1025
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker run -p 8025:8025 -p 1025:1025 -d --name mailhog mailhog/mailhog:v1.0.1
    # start database container, with env variables
    - docker run --env POSTGRES_USER --env POSTGRES_DB --env POSTGRES_PASSWORD -d --name db postgres:18
    # start backend container, with modified entrypoint for testing and env variables
    - docker run --entrypoint /app/mvnw --env POSTGRES_USER --env POSTGRES_DB --env POSTGRES_PASSWORD --env DB_URL --env MAIL_HOST --env MAIL_PORT --env JWT_SECRET="$JWT_SECRET" --env REFRESH_TOKEN_VALUE="$REFRESH_TOKEN_HMAC_SECRET" --link "db:database" --link "mailhog:mailhog" --name backend "${CI_REGISTRY_IMAGE:-projekt}/backend:${CI_COMMIT_SHA:-local}" test

