stages:
  - build
  - test_backend
  - test_frontend
backend-test:
  stage: test_backend
  image: eclipse-temurin:25
  script:
    # start backend container, with modified entrypoint for testing
    - cd projekt/backend
    - ./mvnw clean test
frontend-test:
  stage: test_frontend
  image: node:25.2.1-alpine
  script:
    - cd projekt/frontend
    - npm install
    - npm run test run
build-job:
  stage: build
  image: docker:24.0.5-cli
  services:
    - name: docker:24.0.5-dind
      alias: docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - touch projekt/.env
  script:
    - cd projekt
    - docker compose create --build
    - docker compose push
  after_script:
    - docker compose -f projekt/compose.yml down
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never
