services:
  db:
    image: postgres:18
    env_file:
      - path: .env
        required: false
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  backend:
    image: "${CI_REGISTRY_IMAGE:-projekt}/backend:${CI_COMMIT_SHA:-local}"
    build: backend
    env_file:
      - path: .env
        required: false
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db:database"
    restart: on-failure
  frontend:
    image: "${CI_REGISTRY_IMAGE:-projekt}/frontend:${CI_COMMIT_SHA:-local}"
    build: frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "8080:80"