services:
  db:
    image: "postgres:18"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "{t87R@ZH4ye&"
      POSTGRES_DB: "db_sse_project"
    ports:
        - "5432:5432"
    volumes:
        - db_data:/var/lib/postgresql/data

volumes:
  db_data: