version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/projekt"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    assignees:
        - "kalt09"
  - package-ecosystem: "docker"
    directories:
      - "/projekt/backend"
      - "/projekt/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    assignees:
      - "@kalt09"
    target-branch: "7-dependency-agent-einstellen"
  - package-ecosystem: "maven"
    directory: "/projekt/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    assignees:
      - "@kalt09"
  - package-ecosystem: "npm"
    directory: "/projekt/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    assignees:
      - "@kalt09"