version: 2
updates:
  - package-ecosystem: docker-compose
    directory: /projekt
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: /projekt/backend
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /projekt/frontend
    schedule:
      interval: daily