spring.application.name=backend
server.port=8080

#spring.config.import=optional:file:.env[.properties],optional:classpath:.env[.properties]
spring.datasource.url=${DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.data-locations=classpath:db/data.sql
spring.sql.init.mode=always
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.springframework.security.web.csrf=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.root=WARN
logging.level.com.projektsse=TRACE

logging.level.org.openpolicyagent.opa.springboot=TRACE

opa.enabled=true
opa.url=http://localhost:8181
opa.decision.path=/api/v1/data/authz/allow
opa.cache.enabled=true
opa.cache.ttl=300000

# Wurde mit openssl rand -hex 64 generiert
jwt.secret=${JWT_SECRET}
# 10 Minuten
jwt.access-token-expiration=10

refreshToken.value=${REFRESH_TOKEN_HMAC_SECRET}

# init
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.test-connection=false

# Prod
app.cookie.secure=false

