spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/db_sse_project
spring.datasource.username=postgres
spring.datasource.password={t87R@ZH4ye&

spring.jpa.hibernate.ddl-auto=validate