FROM node:25.2.1-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8080

CMD ["npm", "run", "dev", "--", "--host", "--port", "8080"]

# RUN npm run build

# FROM nginx:1.29.4-alpine

# COPY nginx.dev.conf /etc/nginx/conf.d/default.conf
# COPY --from=build /app/dist /usr/share/nginx/html

# RUN touch /var/run/nginx.pid
# RUN chown -R nginx:nginx /var/cache/nginx && \
#    chown -R nginx:nginx /var/log/nginx && \
#    chown -R nginx:nginx /etc/nginx/conf.d && \
#    chown nginx:nginx /var/run/nginx.pid

# USER nginx

# CMD ["nginx","-g","daemon off;"]

