limit_req_zone $binary_remote_addr zone=addr:10m rate=1r/s;

server {
    listen 8080;
    server_name localhost;
    return 301 https://$host:8081$request_uri;
}
server {
    listen 8081 ssl;
    server_name localhost;
    ssl_certificate /app/ssl/note-app.crt;
    ssl_certificate_key /app/ssl/note-app.key;

    limit_req zone=addr burst=8 nodelay;

    #set $csp_nonce $request_id;

    # React/Vite Build
    root /usr/share/nginx/html;
    index index.html;

    # Frontend-Routing (SPA)
    location = / {
        return 301 https://$host:$request_port/documents/public;
    }

    location / {
        try_files $uri $uri/ /index.html;

        #sub_filter_once off;
        #sub_filter_types *;
        #sub_filter '{{CSP_NONCE}}' $csp_nonce;
    }

    add_header Content-Security-Policy "
        default-src 'self';
        script-src 'self' https: 'unsafe-inline';
        style-src 'self' 'unsafe-inline';
        img-src 'self' https: data:;
        frame-src https://www.youtube-nocookie.com;
        connect-src 'self';
        object-src 'none';
        base-uri 'none';
        frame-ancestors 'none';
    " always;

    # API -> Backend-Service im Docker-Netzwerk
    location /api/ {
        proxy_pass         http://backend:8080;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;

        # proxy_set_header   Cookie $http_cookie;
        # proxy_pass_header  Set-Cookie;
    }
}